name: Node.js CI Build

on:
  pull_request:
    branches: [master]

jobs:
  version:
    name: Ensure package.json version is bumped
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ensure version is bumped
        uses: del-systems/check-if-version-bumped@v1

  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - run: npm ci
      - run: npm test
