name: Ensure package.json version is bumped

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ensure version is bumped
        uses: del-systems/check-if-version-bumped@v1
